# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

version: 2
# see options in https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: pip
    directory: /
    commit-message:
      prefix: "build"
    labels: ["type: build"]
    groups:
      python-main-deps:
        patterns: ["*"]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: .github
    commit-message:
      prefix: "ci"
    labels: ["type: ci"]
    groups:
      github-action-deps:
        patterns: ["*"]
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: "build"
    labels: ["type: build"]
    groups:
      docker-deps:
        patterns: ["*"]
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: /
    commit-message:
      prefix: "build"
    labels: ["type: build"]
    groups:
      npm-main-deps:
        patterns: ["*"]
    schedule:
      interval: weekly
