# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to science-notebook-template
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/science-notebook-template
# SPDX-License-Identifier: Apache-2.0

name: "🐛 Bug"
description: "Bug report"
labels:
  - bug

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: details
    validations:
      required: true
# Uncomment these if they're relevant:
#  - type: dropdown
#    id: os
#    attributes:
#      label: What OS types are you seeing the problem on?
#      multiple: true
#      options:
#        - Windows
#        - Linux
#        - macOS
#    validations:
#      required: false
#  - type: dropdown
#    id: browsers
#    attributes:
#      label: What browsers are you seeing the problem on?
#      multiple: true
#      options:
#        - Chrome
#        - Firefox
#        - Edge
#        - Safari
#        - Opera
#        - Samsung Internet
#    validations:
#      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
