# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to science-notebook-template
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/science-notebook-template
# SPDX-License-Identifier: Apache-2.0

name: "📚 Documentation"
description: "Documentation issue"
labels: ["type: docs"]

body:
  - type: textarea
    id: description
    attributes:
      label: What needs work?
      placeholder: Describe the documentation issue.
    validations:
      required: true
