name: "Feature"
title: "🎁 Feature"
description: "Feature request"
labels: ["kind: new feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: What is the feature request?
      placeholder: Describe the feature you would like.
    validations:
      required: true
